/**
 * Self-hosts the landing page's third-party code.
 *
 * public/index.html is a hand-off file, not an Astro page, so Vite never sees
 * its imports. This integration copies what it needs out of node_modules into
 * public/ before dev or build starts, so the page loads nothing from unpkg or
 * Google Fonts:
 *
 *   public/vendor/three@<version>/three.module.min.js
 *   public/vendor/three@<version>/addons/…   the five postprocessing passes the
 *                                            page imports, plus what they import
 *   public/fonts/landing.css + *.woff2       Archivo (wght + wdth axes),
 *                                            IBM Plex Sans and Mono 400/500
 *
 * Both directories are generated (see .gitignore). The page's import map and
 * stylesheet link name these paths; `npm run test:dist` fails if one is missing.
 */
import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, posix } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const modules = join(root, 'node_modules');

/** Addons public/index.html imports from `three/addons/`. */
const ADDONS = [
  'postprocessing/EffectComposer.js',
  'postprocessing/RenderPass.js',
  'postprocessing/UnrealBloomPass.js',
  'postprocessing/ShaderPass.js',
  'postprocessing/OutputPass.js',
];

/** Fontsource stylesheets for the families and weights the page's CSS uses. */
const FONT_CSS = [
  // Archivo is set at weights 500–800 and font-stretch 108–125%: the variable
  // "standard" cut carries both axes. The page names the family 'Archivo'.
  { css: '@fontsource-variable/archivo/standard.css', family: ['Archivo Variable', 'Archivo'] },
  { css: '@fontsource/ibm-plex-sans/latin-400.css' },
  { css: '@fontsource/ibm-plex-sans/latin-500.css' },
  { css: '@fontsource/ibm-plex-mono/latin-400.css' },
  { css: '@fontsource/ibm-plex-mono/latin-500.css' },
];

function copy(from, to) {
  mkdirSync(dirname(to), { recursive: true });
  copyFileSync(from, to);
}

function vendorThree() {
  const src = join(modules, 'three');
  const { version } = JSON.parse(readFileSync(join(src, 'package.json'), 'utf8'));
  const out = join(root, 'public', 'vendor');
  rmSync(out, { recursive: true, force: true });
  const dest = join(out, `three@${version}`);

  copy(join(src, 'build', 'three.module.min.js'), join(dest, 'three.module.min.js'));

  // Follow relative imports so every file an addon needs comes along.
  const queue = [...ADDONS];
  const seen = new Set();
  while (queue.length) {
    const rel = queue.pop();
    if (seen.has(rel)) continue;
    seen.add(rel);
    const file = join(src, 'examples', 'jsm', rel);
    copy(file, join(dest, 'addons', rel));
    for (const [, spec] of readFileSync(file, 'utf8').matchAll(/from\s+'(\.{1,2}\/[^']+)'/g)) {
      queue.push(posix.normalize(posix.join(posix.dirname(rel), spec)));
    }
  }
}

function vendorFonts() {
  const out = join(root, 'public', 'fonts');
  rmSync(out, { recursive: true, force: true });
  mkdirSync(out, { recursive: true });
  let css = '/* Generated by scripts/vendor-landing.mjs from Fontsource. Do not edit. */\n';
  for (const { css: spec, family } of FONT_CSS) {
    const path = join(modules, spec);
    let text = readFileSync(path, 'utf8').replace(/url\(\.\/files\/([^)]+)\)/g, (_, name) => {
      copy(join(dirname(path), 'files', name), join(out, name));
      return `url(${name})`;
    });
    if (family) text = text.replaceAll(`'${family[0]}'`, `'${family[1]}'`);
    css += text + '\n';
  }
  writeFileSync(join(out, 'landing.css'), css);
}

/** @returns {import('astro').AstroIntegration} */
export default function vendorLanding() {
  return {
    name: 'vendor-landing',
    hooks: {
      'astro:config:setup': ({ logger }) => {
        if (!existsSync(join(modules, 'three'))) throw new Error('three is not installed: run npm install');
        vendorThree();
        vendorFonts();
        logger.info('three.js and landing fonts copied into public/');
      },
    },
  };
}
